version: "3.8"

networks:
  default:
    driver: bridge
  myvlan:
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_PARENT_DEVICE}
    ipam:
      driver: default
      config:
        - subnet: ${MACVLAN_SUBNET} # on my machine, need to be configured

services:
  db:
    build: db/
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      myvlan:
        aliases:
          - ${DB_LOCAL}

  initdb:
    build: initdb/
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_LOCAL
      - INITDB_DATA_FOLDER
      - INITDB_DATA_FILENAME
    command: "python3 init.py"
    volumes:
      - ${INITDB_DATA}:${INITDB_DATA_FOLDER}:ro
    depends_on:
      - db
    networks:
      myvlan:
        aliases:
          - ${INITDB_LOCAL}

  rest_api:
    build: rest_api/
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_LOCAL
      - REST_API_GLOBAL
      - REST_API_LOCAL_PORT
    command: "python3 rest_api.py"
    depends_on:
      - db
      - initdb
    ports:
      - ${REST_API_LOCAL_PORT}:${REST_API_GLOBAL_PORT}
    networks:
      myvlan:
        aliases:
          - ${REST_API_LOCAL}
      default:
        aliases:
          - ${REST_API_GLOBAL}
